### ISSUE TITLE
Infinite loop documentation for language server

### ISSUE THREAD

**Issue by ianchanning** [reasonml-editor/vim-reason-plus#14]
For the language server installation (https://github.com/reasonml-editor/vim-reason-plus#language-server-installation) there is this comment:

> See https://github.com/jaredly/reason-language-server#vim for language-server installation and configuration.

The reason-language-server documentation suggests:

> Install the [reason-vim plugin](https://github.com/reasonml-editor/vim-reason-plus), following the readme.

So I can't figure out how you're supposed to install the two together

**Comment by SeeThruHead** [comment]
also cannot figure out where
`/absolute/path/to/reason-language-server.exe'`
is, reason-language-server#vim sends you back here
and https://github.com/jaredly/reason-language-server doesn't seem to offer any information for regular users rather than contributors.

**Comment by ianchanning** [comment]
@SeeThruHead The Vim section of the reason-language-server was missing a step that tells you to go to the releases page. I've [submitted a PR](https://github.com/jaredly/reason-language-server/pull/156) to fix this. It's missing this line:

> Download the `your-platform.zip` file from the [latest release](https://github.com/jaredly/reason-language-server/releases), unzip it, and put the `reason-language-server.exe` file somewhere.

**Comment by ianchanning** [comment]
The reason-language-server README has been updated now, so I think this issue is no longer relevant.
