### ISSUE TITLE
[LC] Not found!

### ISSUE THREAD

**Issue by cabaalexander** [reasonml-editor/vim-reason-plus#24]
I don't know what I'm missing, I think I followed the readme and installed all that I need.

When I call this on `nvim` 👇 
```vim
:call LanguageClient_textDocument_definition()
```

I get this error `[LC] Not found!`

Any idea what could that be? 🤔

**Comment by anmonteiro** [comment]
Thanks for finding this. The commands in the README were wrong. 

it should actually be `LanguageClient#textDocument_definition()`
